### ISSUE TITLE
Npm run build -  SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by gooddaytoday** [usablica/intro.js#1644]
## Description

1. Cloned repository
2. Run `npm install`
3. Run `npm run build`

Error:

```
> intro.js@5.0.0 build \thirdparty\introjs_build
> rollup -c

[!] SyntaxError: Cannot use import statement outside a module
\thirdparty\introjs_build\rollup.config.js:1
import babel from 'rollup-plugin-babel';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (\thirdparty\introjs_build\node_modules\rollup\dist\shared\loadConfigFile.js:617:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at loadConfigFromBundledFile (\thirdparty\introjs_build\node_modules\rollup\dist\shared\loadConfigFile.js:622:42)
    at loadConfigFile (\thirdparty\introjs_build\node_modules\rollup\dist\shared\loadConfigFile.js:565:11)
```

## Environment

NodeJS version: 12.22.7

**Comment by gooddaytoday** [comment]
Temporary solution:

`npm install rollup@~2.66`

Or just wait until [2.74.0](https://www.npmjs.com/package/rollup/v/2.74.0) will be install with `npm install` - it was fixed just 6 hours ago in https://github.com/rollup/rollup/issues/4446

**Comment by gooddaytoday** [comment]
It seems that current rollup 2.70.1 works well on every computer except mine, so I'll close issue.
